[package]
name = "taiko-reth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
# reth
reth = { workspace = true, features = ["taiko"] }
reth-node-core.workspace = true
reth-primitives = { workspace = true, features = ["taiko"] }
# taiko
taiko-reth-node.workspace = true

[features]
asm-keccak = ["reth-node-core/asm-keccak", "reth-primitives/asm-keccak"]

[lints]
workspace = true

[[bin]]
name = "taiko-reth"
path = "src/main.rs"
