[package]
name = "taiko-reth-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-evm.workspace = true
reth-primitives.workspace = true
reth-prune-types.workspace = true
reth-revm.workspace = true
[lints]
workspace = true
